# Generated by Django 5.1.4 on 2025-01-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_hidden',
        ),
    ]
